### ISSUE TITLE
Web UI is sending 307 redirect when lanuch

### ISSUE THREAD

**Issue by Eisaichen** [sipeed/NanoKVM-Pro#16]
<img width="681" height="550" alt="Image" src="https://github.com/user-attachments/assets/2b27c464-a94c-42d8-8589-bc6ff4f18309" />

When accessing the web UI, a 307 redirect will issue to the user, the target URL will be the IP address of the KVM.
This makes the NanoKVM unable to be used behind a reverse proxy. Is there a way to disable this behavior?

**Comment by wj-xiao** [comment]
We fixed a related issue in version [1.1.9](https://github.com/sipeed/NanoKVM-Pro/blob/main/CHANGELOG.md#119-2025-10-31). Could you please try updating again?

**Comment by Eisaichen** [comment]
@wj-xiao Sorry but this is still happening with the latest version 1.2.1
